import lily2 from '../../assets/images/lily2.jpg' 
import fantasy5 from '../../assets/images/fantasy5.jpg'
import evening from '../../assets/images/evening.jpg'
import fantasy2 from '../../assets/images/fantasy2.jpg'
import flowers3 from '../../assets/images/flowers3.jpg'
import girl7 from '../../assets/images/girl7.jpg'
import nature3 from '../../assets/images/nature3.jpg' 
import wiwi4 from '../../assets/images/wiwi4.jpg' 
import fantasy4 from '../../assets/images/fantasy4.jpg' 
import mountains from '../../assets/images/mountains.jpg' 
import fantasy10 from '../../assets/images/fantasy10.jpg' 
import nature4 from '../../assets/images/nature4.jpg'
import girl1 from '../../assets/images/girl1.jpg'
import fon from '../../assets/images/fon.jpg'

export default [lily2, fantasy5, evening, fantasy2,  flowers3, girl7, nature3, wiwi4, fantasy4, mountains, fantasy10, nature4, girl1, fon];